import { mkdir, stat, writeFile } from "node:fs/promises";
import { join, posix } from "node:path";
import { parseArgs } from "../core/args.ts";
import { writeConfig } from "../core/config.ts";
import { gitToplevel, isGitRepo } from "../core/git.ts";
import { loadIgnore, writeDefaultIgnore } from "../core/ignore.ts";
import {
  mapPathFor,
  materializeDirs,
  planMirror,
  writePlaceholderMap,
} from "../core/mirror.ts";
import { absPath, defaultShadowFor } from "../core/paths.ts";

export async function init(argv: string[]): Promise<void> {
  const { positional, flags } = parseArgs(argv);
  const realInput = positional[0];

  if (!realInput) {
    throw new Error("usage: couch-potato init <real-repo-path> [--shadow <dir>]");
  }

  const real = absPath(realInput);
  const realStat = await stat(real).catch(() => null);
  if (!realStat?.isDirectory()) {
    throw new Error(`not a directory: ${real}`);
  }
  if (!(await isGitRepo(real))) {
    throw new Error(`not a git repo: ${real}`);
  }

  const realToplevel = await gitToplevel(real);
  if (realToplevel !== real) {
    throw new Error(`expected git toplevel, got ${real} (toplevel: ${realToplevel})`);
  }

  const shadow = flags.shadow
    ? absPath(String(flags.shadow))
    : defaultShadowFor(real);

  const existing = await stat(shadow).catch(() => null);
  if (existing) {
    throw new Error(`shadow already exists: ${shadow} (refusing to overwrite)`);
  }

  console.log(`real:   ${real}`);
  console.log(`shadow: ${shadow}`);
  console.log("");

  await mkdir(shadow, { recursive: true });
  await writeDefaultIgnore(shadow);

  const ig = await loadIgnore(shadow);
  const plan = await planMirror(real, "HEAD", ig);
  await materializeDirs(shadow, plan.dirs);

  // Group files by directory.
  const filesByDir = new Map<string, typeof plan.files>();
  for (const f of plan.files) {
    const parent = posix.dirname(f.path);
    const key = parent === "." ? "" : parent;
    let arr = filesByDir.get(key);
    if (!arr) { arr = []; filesByDir.set(key, arr); }
    arr.push(f);
  }

  // Group child dirs by parent.
  const childrenByDir = new Map<string, string[]>();
  for (const d of plan.dirs) {
    if (d === "") continue;
    const parent = posix.dirname(d);
    const key = parent === "." ? "" : parent;
    const childName = posix.basename(d);
    let arr = childrenByDir.get(key);
    if (!arr) { arr = []; childrenByDir.set(key, arr); }
    arr.push(childName);
  }

  for (const d of plan.dirs) {
    const files = filesByDir.get(d) ?? [];
    const children = (childrenByDir.get(d) ?? []).sort();
    const mapPath = mapPathFor(shadow, d);
    await writePlaceholderMap(mapPath, d, files, children);
  }

  await writeConfig(shadow, {
    version: 1,
    target: real,
    ref: "HEAD",
    createdAt: new Date().toISOString(),
  });

  await writeRootClaudeMd(shadow, real);

  const dirCount = plan.dirs.length;
  const fileCount = plan.files.length;
  console.log(`mirrored ${dirCount} directories, ${fileCount} files`);
  console.log(`wrote ${dirCount} _MAP.md placeholders`);
  console.log(`ignore patterns: .couch-potato/ignore (edit to customize)`);
  console.log("");
  console.log(`next: cd ${real} && couch-potato sync`);
  console.log("      (or `couch-potato sync --scope <subpath>` to scan incrementally)");
}

async function writeRootClaudeMd(shadow: string, real: string): Promise<void> {
  const body = `# couch-potato shadow

This directory is a **code virtual map** for a real repository. The directory
structure mirrors the target repo, but files contain semantic summaries
(\`_MAP.md\`) instead of source code.

- **Target repo:** \`${real}\`
- **Generated by:** couch-potato

Coverage may be partial: dirs not yet scanned by \`couch-potato sync\` show
\`status: placeholder\` in their \`_MAP.md\`. The shadow grows incrementally
as you run \`couch-potato sync --scope <subpath>\` over different areas.

## How to read this shadow

1. Start at the root \`_MAP.md\` for a global index.
2. Drill into subdirectories' \`_MAP.md\` only when you need detail.
3. Each \`_MAP.md\` records git blob hashes per file. If they don't match the
   real repo's current \`git ls-tree HEAD\` output, the map is **stale** for
   that file — read the real source instead of trusting the summary.

## When implementing

Do NOT edit code in this shadow. To make actual code changes, start a
**separate** Claude session inside the target repo:

\`\`\`
cd ${real}
claude
\`\`\`

That session will pick up the target repo's own \`CLAUDE.md\` (if any) and
operate against real source files.
`;
  await writeFile(join(shadow, "CLAUDE.md"), body, "utf8");
}
